config/routes.rb
Miner::Application.routes.draw do
  resources :capstones

  resources :indices

  post "welcome/new"
  post "welcome/create"
  get "welcome/create"
  post "welcome/calculate"
  post "welcome/start"

  resources :dtcs

  resources :fitments

  root 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/fitment.rb
class Fitment < ActiveRecord::Base
  has_and_belongs_to_many :dtcs
end

app/controllers/fitments_controller.rb
class FitmentsController < ApplicationController
  before_action :set_fitment, only: [:show, :edit, :update, :destroy]

  # GET /fitments
  # GET /fitments.json
  def index
    @fitments = Fitment.all
  end

  # GET /fitments/1
  # GET /fitments/1.json
  def show
  end

  # GET /fitments/new
  def new
    @fitment = Fitment.new
  end

  # GET /fitments/1/edit
  def edit
  end

  # POST /fitments
  # POST /fitments.json
  def create
    @fitment = Fitment.new(fitment_params)

    respond_to do |format|
      if @fitment.save
        format.html { redirect_to @fitment, notice: 'Fitment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fitment }
      else
        format.html { render action: 'new' }
        format.json { render json: @fitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fitments/1
  # PATCH/PUT /fitments/1.json
  def update
    respond_to do |format|
      if @fitment.update(fitment_params)
        format.html { redirect_to @fitment, notice: 'Fitment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fitments/1
  # DELETE /fitments/1.json
  def destroy
    @fitment.destroy
    respond_to do |format|
      format.html { redirect_to fitments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fitment
      @fitment = Fitment.find(params[:id])
      @dtcs = Dtc.all

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fitment_params
      params.require(:fitment).permit(:make, :year, :model, :engine, :dtc_ids => [])
    end
end

app/helpers/fitments_helper.rb
module FitmentsHelper
end

app/views/fitments/_form.html.erb
<%= simple_form_for(@fitment) do |f| %>
  <% if @fitment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fitment.errors.count, "error") %> prohibited this fitment from being saved:</h2>

      <ul>
      <% @fitment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :make %>
    <%= f.input :year %>
    <%= f.input :model %>
    <%= f.input :engine %>
    <%= f.association :dtcs %>

    <%= f.submit %>

<% end %>

app/views/fitments/edit.html.erb
<h1>Editing fitment</h1>

<%= render 'form' %>

<%= link_to 'Show', @fitment %> |
<%= link_to 'Back', fitments_path %>

app/views/fitments/index.html.erb
<h1>Listing fitments</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Year</th>
      <th>Model</th>
      <th>Engine</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fitments.each do |fitment| %>
      <tr>
        <td><%= fitment.make %></td>
        <td><%= fitment.year %></td>
        <td><%= fitment.model %></td>
        <td><%= fitment.engine %></td>
        <th>DTC's</th>
        <td><%= fitment.dtcs.map {|c| c.code}.join(', ') %></td>

        <td><%= link_to 'Show', fitment %></td>
        <td><%= link_to 'Edit', edit_fitment_path(fitment) %></td>
        <td><%= link_to 'Destroy', fitment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fitment', new_fitment_path %>

app/views/fitments/new.html.erb
<h1>New fitment</h1>

<%= render 'form' %>

<%= link_to 'Back', fitments_path %>

app/views/fitments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @fitment.make %>
</p>

<p>
  <strong>Year:</strong>
  <%= @fitment.year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @fitment.model %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @fitment.engine %>
</p>

<p>
  <strong>DTC Codes:</strong>
  <%= @fitment.dtcs.map {|c| c.code}.join(', ') %>
</p>

<%= link_to 'Edit', edit_fitment_path(@fitment) %> |
<%= link_to 'Back', fitments_path %>