config/routes.rb
Miner::Application.routes.draw do
  resources :capstones

  resources :indices

  post "welcome/new"
  post "welcome/create"
  get "welcome/create"
  post "welcome/calculate"
  post "welcome/start"

  resources :dtcs

  resources :fitments

  root 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/dtc.rb
class Dtc < ActiveRecord::Base
  has_and_belongs_to_many :fitments
end

app/controllers/dtcs_controller.rb
class DtcsController < ApplicationController
  before_action :set_dtc, only: [:show, :edit, :update, :destroy]

  # GET /dtcs
  # GET /dtcs.json
  def index
    @dtcs = Dtc.all
  end

  # GET /dtcs/1
  # GET /dtcs/1.json
  def show
  end

  # GET /dtcs/new
  def new
    @dtc = Dtc.new
  end

  # GET /dtcs/1/edit
  def edit
  end

  # POST /dtcs
  # POST /dtcs.json
  def create
    @dtc = Dtc.new(dtc_params)

    respond_to do |format|
      if @dtc.save
        format.html { redirect_to @dtc, notice: 'Dtc was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dtc }
      else
        format.html { render action: 'new' }
        format.json { render json: @dtc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dtcs/1
  # PATCH/PUT /dtcs/1.json
  def update
    respond_to do |format|
      if @dtc.update(dtc_params)
        format.html { redirect_to @dtc, notice: 'Dtc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dtc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dtcs/1
  # DELETE /dtcs/1.json
  def destroy
    @dtc.destroy
    respond_to do |format|
      format.html { redirect_to dtcs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dtc
      @dtc = Dtc.find(params[:id])
      @fitments = Fitment.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dtc_params
      params.require(:dtc).permit(:code, :description, :meaning, :system, :source, :fitment_ids => [])
    end
end

app/helpers/dtcs_helper.rb
module DtcsHelper
end

app/views/dtcs/_form.html.erb
<%= simple_form_for @dtc do |f| %>
  <% if @dtc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dtc.errors.count, "error") %> prohibited this dtc from being saved:</h2>

      <ul>
      <% @dtc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :code %>
    <%= f.input :description %>
    <%= f.input :meaning %>
    <%= f.input :source %>
    <%= f.input :system %>
    <%= f.association :fitments %>

    <%= f.submit %>

<% end %>

app/views/dtcs/edit.html.erb
<h1>Editing dtc</h1>

<%= render 'form' %>

<%= link_to 'Show', @dtc %> |
<%= link_to 'Back', dtcs_path %>

app/views/dtcs/index.html.erb
<h1>Listing dtcs</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Meaning</th>
      <th>Source</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dtcs.each do |dtc| %>
      <tr>
        <td><%= dtc.code %></td>
        <td><%= dtc.description %></td>
        <td><%= dtc.meaning %></td>
        <td><%= dtc.system %></td>
        <td><%= dtc.source %></td>
        <th>Fitments</th>
        <td><%= dtc.fitments.map {|c| c.make+c.year+c.model+c.engine}.join(', ') %></td>
        <td><%= link_to 'Show', dtc %></td>
        <td><%= link_to 'Edit', edit_dtc_path(dtc) %></td>
        <td><%= link_to 'Destroy', dtc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dtc', new_dtc_path %>

app/views/dtcs/new.html.erb
<h1>New dtc</h1>

<%= render 'form' %>

<%= link_to 'Back', dtcs_path %>

app/views/dtcs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @dtc.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @dtc.description %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @dtc.meaning %>
</p>

<p>
  <strong>Source:</strong>
  <%= @dtc.source %>
</p>

<p>
  <strong>System:</strong>
  <%= @dtc.system %>
</p>

<p>
  <strong>Fitments:</strong>
  <%= @dtc.fitments.map {|c|  c.make+c.year+c.model+c.engine}.join(', ') %>
</p>

<%= link_to 'Edit', edit_dtc_path(@dtc) %> |
<%= link_to 'Back', dtcs_path %>