config/routes.rb
Miner::Application.routes.draw do
  resources :capstones

  resources :indices

  post "welcome/new"
  post "welcome/create"
  get "welcome/create"
  post "welcome/calculate"
  post "welcome/start"

  resources :dtcs

  resources :fitments

  root 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/capstone.rb
class Capstone < ActiveRecord::Base
end

app/controllers/capstones_controller.rb
class CapstonesController < ApplicationController
  before_action :set_capstone, only: [:show, :edit, :update, :destroy]

  # GET /capstones
  # GET /capstones.json
  def index
    @capstones = Capstone.all
  end

  # GET /capstones/1
  # GET /capstones/1.json
  def show
  end

  # GET /capstones/new
  def new
    @capstone = Capstone.new
  end

  # GET /capstones/1/edit
  def edit
  end

  # POST /capstones
  # POST /capstones.json
  def create
    @capstone = Capstone.new(capstone_params)

    respond_to do |format|
      if @capstone.save
        format.html { redirect_to @capstone, notice: 'Capstone was successfully created.' }
        format.json { render action: 'show', status: :created, location: @capstone }
      else
        format.html { render action: 'new' }
        format.json { render json: @capstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capstones/1
  # PATCH/PUT /capstones/1.json
  def update
    respond_to do |format|
      if @capstone.update(capstone_params)
        format.html { redirect_to @capstone, notice: 'Capstone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @capstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capstones/1
  # DELETE /capstones/1.json
  def destroy
    @capstone.destroy
    respond_to do |format|
      format.html { redirect_to capstones_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capstone
      @capstone = Capstone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capstone_params
      params.require(:capstone).permit(:index, :number)
    end
end

app/helpers/capstones_helper.rb
module CapstonesHelper
end

app/views/capstones/_form.html.erb
<%= simple_form_for(@capstone) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :index %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/capstones/edit.html.erb
<h1>Editing capstone</h1>

<%= render 'form' %>

<%= link_to 'Show', @capstone %> |
<%= link_to 'Back', capstones_path %>

app/views/capstones/index.html.erb
<h1>Listing capstones</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @capstones.each do |capstone| %>
      <tr>
        <td><%= capstone.index %></td>
        <td><%= capstone.number %></td>
        <td><%= link_to 'Show', capstone %></td>
        <td><%= link_to 'Edit', edit_capstone_path(capstone) %></td>
        <td><%= link_to 'Destroy', capstone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capstone', new_capstone_path %>

app/views/capstones/new.html.erb
<h1>New capstone</h1>

<%= render 'form' %>

<%= link_to 'Back', capstones_path %>

app/views/capstones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @capstone.index %>
</p>

<p>
  <strong>Number:</strong>
  <%= @capstone.number %>
</p>

<%= link_to 'Edit', edit_capstone_path(@capstone) %> |
<%= link_to 'Back', capstones_path %>