config/routes.rb
Miner::Application.routes.draw do
  resources :capstones

  resources :indices

  post "welcome/new"
  post "welcome/create"
  get "welcome/create"
  post "welcome/calculate"
  post "welcome/start"

  resources :dtcs

  resources :fitments

  root 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController
  before_action :set_index, only: [:show, :edit, :update, :destroy]

  # GET /indices
  # GET /indices.json
  def index
    @indices = Index.all
  end

  # GET /indices/1
  # GET /indices/1.json
  def show
  end

  # GET /indices/new
  def new
    @index = Index.new
  end

  # GET /indices/1/edit
  def edit
  end

  # POST /indices
  # POST /indices.json
  def create
    @index = Index.new(index_params)

    respond_to do |format|
      if @index.save
        format.html { redirect_to @index, notice: 'Index was successfully created.' }
        format.json { render action: 'show', status: :created, location: @index }
      else
        format.html { render action: 'new' }
        format.json { render json: @index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indices/1
  # PATCH/PUT /indices/1.json
  def update
    respond_to do |format|
      if @index.update(index_params)
        format.html { redirect_to @index, notice: 'Index was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indices/1
  # DELETE /indices/1.json
  def destroy
    @index.destroy
    respond_to do |format|
      format.html { redirect_to indices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_index
      @index = Index.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def index_params
      params.require(:index).permit(:miner, :mode, :make, :year, :model, :engine, :system, :dtc)
    end
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/views/indices/_form.html.erb
<%= simple_form_for(@index) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :miner %>
    <%= f.input :mode %>
    <%= f.input :make %>
    <%= f.input :year %>
    <%= f.input :model %>
    <%= f.input :engine %>
    <%= f.input :system %>
    <%= f.input :dtc %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/indices/edit.html.erb
<h1>Editing index</h1>

<%= render 'form' %>

<%= link_to 'Show', @index %> |
<%= link_to 'Back', indices_path %>

app/views/indices/index.html.erb
<h1>Listing indices</h1>

<table>
  <thead>
    <tr>
      <th>Miner</th>
      <th>Mode</th>
      <th>Make</th>
      <th>Year</th>
      <th>Model</th>
      <th>Engine</th>
      <th>System</th>
      <th>Dtc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @indices.each do |index| %>
      <tr>
        <td><%= index.miner %></td>
        <td><%= index.mode %></td>
        <td><%= index.make %></td>
        <td><%= index.year %></td>
        <td><%= index.model %></td>
        <td><%= index.engine %></td>
        <td><%= index.system %></td>
        <td><%= index.dtc %></td>
        <td><%= link_to 'Show', index %></td>
        <td><%= link_to 'Edit', edit_index_path(index) %></td>
        <td><%= link_to 'Destroy', index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Index', new_index_path %>

app/views/indices/new.html.erb
<h1>New index</h1>

<%= render 'form' %>

<%= link_to 'Back', indices_path %>

app/views/indices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Miner:</strong>
  <%= @index.miner %>
</p>

<p>
  <strong>Mode:</strong>
  <%= @index.mode %>
</p>

<p>
  <strong>Make:</strong>
  <%= @index.make %>
</p>

<p>
  <strong>Year:</strong>
  <%= @index.year %>
</p>

<p>
  <strong>Model:</strong>
  <%= @index.model %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @index.engine %>
</p>

<p>
  <strong>System:</strong>
  <%= @index.system %>
</p>

<p>
  <strong>Dtc:</strong>
  <%= @index.dtc %>
</p>

<%= link_to 'Edit', edit_index_path(@index) %> |
<%= link_to 'Back', indices_path %>